# Generated by Django 3.2.5 on 2021-07-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ids_ecosystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco', models.CharField(max_length=1)),
                ('ecoName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ids_ecosystem',
            },
        ),
        migrations.CreateModel(
            name='ids_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.IntegerField()),
                ('locType', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'ids_location',
            },
        ),
        migrations.CreateModel(
            name='kpi_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locType', models.CharField(max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('palayValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agriValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gdpValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ids_location')),
            ],
            options={
                'db_table': 'kpi_value',
            },
        ),
        migrations.CreateModel(
            name='kpi_sua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locType', models.CharField(max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('SUBeginningStocks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SUProduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SUImports', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UTExports', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UTSeeds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UTFeedsWaste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UTProcessing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UTEndingStocks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UTPerCapitaKg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UTPerCapitaGram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ids_location')),
            ],
            options={
                'db_table': 'kpi_sua',
            },
        ),
        migrations.CreateModel(
            name='kpi_prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locType', models.CharField(max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('farmgatePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('WholesalePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retailPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ids_location')),
            ],
            options={
                'db_table': 'kpi_prices',
            },
        ),
        migrations.CreateModel(
            name='kpi_pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locType', models.CharField(max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=1)),
                ('eco', models.CharField(max_length=1)),
                ('estProduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('areaHarv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yieldEst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ids_location')),
            ],
            options={
                'db_table': 'kpi_pay',
            },
        ),
        migrations.CreateModel(
            name='kpi_cpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locType', models.CharField(max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('cpiAll', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cpiFood', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cpiRice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('locCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ids_location')),
            ],
            options={
                'db_table': 'kpi_cpi',
            },
        ),
        migrations.CreateModel(
            name='kpi_costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locType', models.CharField(max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('costProduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ids_location')),
            ],
            options={
                'db_table': 'kpi_costs',
            },
        ),
    ]
