# Generated by Django 3.2.5 on 2021-07-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ids_location',
            name='locName',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ids_location',
            name='parent',
            field=models.SmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ids_location',
            name='sort',
            field=models.SmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ids_location',
            name='locCode',
            field=models.SmallIntegerField(),
        ),
    ]
