# Generated by Django 3.2.5 on 2021-07-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210708_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpi_prices',
            old_name='WholesalePrice',
            new_name='wholesalePrice',
        ),
        migrations.AddField(
            model_name='kpi_prices',
            name='WholesaleSpPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='kpi_prices',
            name='retailSpPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
