# Generated by Django 3.2.5 on 2021-07-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210708_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='kpi_costscom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locName', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('materialInputs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hiredLabor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('OFELabor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('machine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('irrigation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('landRent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interestCapital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('otherInputs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'kpi_costscom',
            },
        ),
        migrations.CreateModel(
            name='kpi_npk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('nperha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pperha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kperha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'kpi_npk',
            },
        ),
        migrations.CreateModel(
            name='kpi_percapita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('PerCapitaKg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PerCapitaGram', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'kpi_percapita',
            },
        ),
        migrations.CreateModel(
            name='rb_farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('aveFarmSize', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tstatusOwned', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tstatusAmort', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tstatusLessee', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tstatusTenant', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tstatusOthers', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('areaLessOne', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('areaOneTwo', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('areaTwoThree', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('areaMoreThree', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_farm',
            },
        ),
        migrations.CreateModel(
            name='rb_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('monthlyIncome', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('riceSource', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('vegetableSource', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('selfEmployesSource', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('liveStockSource', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('salarySource', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('otheSource', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('abovePovertyShare', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('belowPovertShare', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_income',
            },
        ),
        migrations.CreateModel(
            name='rb_socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sexMale', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sexFemale', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cstatusSingle', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cstatusMarried', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cstatusWidow', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cstatusSeparated', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('yrsSchooling', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('yrsFarmExp', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('hhSize', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('orgMember', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('withTraining', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_socio',
            },
        ),
    ]
