# Generated by Django 3.2.5 on 2021-07-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_kpi_costscom_kpi_npk_kpi_percapita_rb_farm_rb_income_rb_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='kpi_pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('population', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'kpi_pop',
            },
        ),
    ]
