# Generated by Django 3.2.5 on 2021-07-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_kpi_pop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi_pop',
            name='population',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
