# Generated by Django 3.2.5 on 2021-09-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rb_ycost'),
    ]

    operations = [
        migrations.CreateModel(
            name='rb_cropest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('transplant', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('wetDirect', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('dryDirect', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('totalDirect', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('bothMethod', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('transSeedingRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aveSeedingRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_cropest',
            },
        ),
        migrations.CreateModel(
            name='rb_cropsched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('month', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('plant1', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('plant2', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('plant3', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('harv1', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('harv2', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('harv3', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_cropsched',
            },
        ),
        migrations.CreateModel(
            name='rb_fertgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('rank', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('grade', models.CharField(blank=True, max_length=500, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_fertgrade',
            },
        ),
        migrations.CreateModel(
            name='rb_fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('nPerHa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pPerHa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kPerHa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fertPerHa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_fertilizer',
            },
        ),
        migrations.CreateModel(
            name='rb_labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('totalLabor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preHarvest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('harvThreshing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('postHarvest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('permLabor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_labor',
            },
        ),
        migrations.CreateModel(
            name='rb_machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('adoptionRHandtractor', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('adoptionFTiller', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('adoptionMicrotiller', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('adoptionDrumseeder', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('adoptionTransplanter', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('adoptionReaper', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('adoptionCHarvester', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_machine',
            },
        ),
        migrations.CreateModel(
            name='rb_pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('rank', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('brand', models.CharField(blank=True, max_length=500, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_pest',
            },
        ),
        migrations.CreateModel(
            name='rb_seedclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('hybrid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('highInbred', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('goodSeeds', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('farmerSeeds', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_seedclass',
            },
        ),
        migrations.CreateModel(
            name='rb_variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locCode', models.SmallIntegerField()),
                ('locType', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('eco', models.CharField(blank=True, max_length=1, null=True)),
                ('rank', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('variety', models.CharField(blank=True, max_length=500, null=True)),
                ('perocent', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rb_variety',
            },
        ),
    ]
