# Generated by Django 3.2.5 on 2021-09-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rb_cropest_rb_cropsched_rb_fertgrade_rb_fertilizer_rb_labor_rb_machine_rb_pest_rb_seedclass_rb_varie'),
    ]

    operations = [
        migrations.AddField(
            model_name='rb_cropest',
            name='directSeedingRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
