# Generated by Django 3.2.5 on 2021-09-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rb_cropest_directseedingrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rb_variety',
            old_name='perocent',
            new_name='percent',
        ),
    ]
